# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Template-Compiled-Plugin-InlineImage
version:      0.02
version_from: lib/HTML/Template/Compiled/Plugin/InlineImage.pm
installdirs:  site
requires:
    GD:                            0
    HTML::Template::Compiled:      0.73
    MIME::Base64:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
